image:
  repository: abdullahalmeshari/demo@sha256
  tag: 8937eda9969427634e0ddd5ab5cc36ab6dd106ed5ecf06b5d300dcc4e77b8251
  pullPolicy: Always

replicaCount: 3
name: suliman-app
Release: suliman-app

healthcheck:
  initialDelaySeconds: 10
  failureThreshold: 2
  successThreshold: 1
  periodSeconds: 10
  timeoutSeconds: 5
  httpGet:
    path: "/"
    port: "http"

service:
  container_port: 3000
  type: ClusterIP
  name: suliman-service
  port: 80
