image:
  repository: abdullahalmeshari/demo@sha256
  tag: 3b337d74966990d64a857ca69a03501cde5248587c8448ece2f49f02be5a9811
  pullPolicy: IfNotPresent

replicaCount: 3
name: suliman-app
Release: suliman-app

healthcheck:
  initialDelaySeconds: 10
  failureThreshold: 2
  successThreshold: 1
  periodSeconds: 10
  timeoutSeconds: 5
  httpGet:
    path: "/"
    port: "http"

service:
  container_port: 3000
  type: ClusterIP
  name: suliman-service
  port: 80