appName: myhelmapp

replicas: 1

namespace: Webapp

port: 80


configmap:
  name: myhelmapp-configmap-v1
  data:
    CUSTOM_HEADER: 'This app was deployed with helm!'

image:
  name: registry.k8s.io/e2e-test-images/agnhost
  tag: 2.40
