appName: myhelmapp

replicas: 1

namespace: Webapp

port: 80


configmap:
  name: myhelmapp-configmap-v1
  data:
    CUSTOM_HEADER: 'This app was deployed with helm!'

image:
  name: k8s.io/kubernetes/test/images/agnhost
  tag: 1.31.1
