apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/instance: {{ .Values.Release }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name }}
      app.kubernetes.io/instance: {{ .Values.Release }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.name }}
        app.kubernetes.io/instance: {{ .Values.Release }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name:  http
              containerPort: {{ .Values.service.container_port }}
              protocol: TCP 
          {{- if .Values.healthcheck }}      
          livenessProbe:
            {{- toYaml .Values.healthcheck | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.healthcheck | nindent 12 }}
          {{end}}
